# Dataset

In [2]:
from database import *
datasetdb = DatasetDB()
datasetdb.get_df()

                                  id   task    size
0                      sangmu_str_MH  [STR]     501
0                      sangmu_str_DI  [STR]     568
0                      sangmu_str_DH  [STR]     566
0                      sangmu_std_MH  [STD]     501
0                      sangmu_std_DI  [STD]     568
0                      sangmu_std_DH  [STD]     566
0                   sangmu_str_MH_v2  [STR]    1491
0                   sangmu_str_DI_v2  [STR]    1840
0                   sangmu_str_DH_v2  [STR]    2208
0                          aihub_rec  [STR]  682525
0                           rec_test  [STR]       3
0                           rec_SVTP  [STR]     645
0                            rec_SVT  [STR]     647
0                         rec_IIIT5K  [STR]    5000
0                           rec_ic15  [STR]    2077
0                           rec_ic13  [STR]     857
0                           rec_ic03  [STR]     860
0                         rec_CUTE80  [STR]     288
0                 outsourcing_v1_rec  [STR]    6252
0      outsourcing_v1(exception)_rec  [STR]    2237
0               outsourcing_v2.1_rec  [STR]    3738
0               outsourcing_v2.2_rec  [STR]    6151
0               outsourcing_v2.3_rec  [STR]     724
0               outsourcing_v2.4_rec  [STR]    1513
0               outsourcing_v2.5_rec  [STR]    1666
0             outsourcing_v2.6.1_rec  [STR]    1043
0             outsourcing_v2.6.2_rec  [STR]    1294
0    outsourcing_v2.3(exception)_rec  [STR]     179
0  outsourcing_v2.6.1(exception)_rec  [STR]     147
0    outsourcing_v2.4(exception)_rec  [STR]     249
0    outsourcing_v2.5(exception)_rec  [STR]     193
0    outsourcing_v2.1(exception)_rec  [STR]     663
0  outsourcing_v2.6.2(exception)_rec  [STR]     144
0    outsourcing_v2.2(exception)_rec  [STR]    1160
0                 outsourcing_v1_det  [STD]    2004
0      outsourcing_v1(exception)_det  [STD]     643
0               outsourcing_v2.1_det  [STD]    1135
0               outsourcing_v2.2_det  [STD]    2070
0               outsourcing_v2.3_det  [STD]     286
0               outsourcing_v2.4_det  [STD]     434
0               outsourcing_v2.5_det  [STD]     500
0             outsourcing_v2.6.1_det  [STD]     297
0             outsourcing_v2.6.2_det  [STD]     303
0    outsourcing_v2.3(exception)_det  [STD]      68
0    outsourcing_v2.1(exception)_det  [STD]     199
0    outsourcing_v2.5(exception)_det  [STD]      48
0    outsourcing_v2.4(exception)_det  [STD]      78
0  outsourcing_v2.6.1(exception)_det  [STD]      39
0  outsourcing_v2.6.2(exception)_det  [STD]      36
0    outsourcing_v2.2(exception)_det  [STD]     392
0        outsourcing1(exception)_str  [STR]    2237
0                   outsourcing1_str  [STR]    6252

In [1]:
datasetdb.get_all_id()

NameError: name 'datasetdb' is not defined